/* DO NOT EDIT THIS FILE - it is machine generated */
/*用不到*/
#include <jni.h>
/* Header for class com_huican_test_NativeLibrary */

#ifndef _Included_com_huican_test_NativeLibrary
#define _Included_com_huican_test_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huican_test_NativeLibrary
 * Method:    getDataFromNative
 * Signature: ()Lcom/huican/test/bean/DataBean;
 */
JNIEXPORT jobject JNICALL Java_com_huican_test_NativeLibrary_getDataFromNative
  (JNIEnv *, jclass);

/*
 * Class:     com_huican_test_NativeLibrary
 * Method:    transferDataToNative
 * Signature: (Lcom/huican/test/bean/DataBean;)V
 */
JNIEXPORT void JNICALL Java_com_huican_test_NativeLibrary_transferDataToNative
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
