/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huican_test_JniTest */

#ifndef _Included_com_huican_test_JniTest
#define _Included_com_huican_test_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huican_test_JniTest
 * Method:    transNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_huican_test_JniTest_transNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
